name: 'Goals '
favicon: null
layout_spectrum: 0.7609299297910184
typography_spectrum: 0.5541126744356006
title: '2016'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42154805385507643
  lightness: 0.9422598218079656
  saturation: 0.7692478557582945
  rhythmicContrast: 0.6096016303636134
purpose: []
