name: 'Goals '
favicon: null
layout_spectrum: 0.99901
typography_spectrum: 1
title: '2016'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020106'
    - '#f8d7aa'
    - '#bf704d'
    - '#8b3616'
    - '#433421'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0
purpose: []
